# Generated by Django 3.1.7 on 2021-03-20 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='date_scheduled')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='date_completed')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OoB.project')),
                ('tags', models.ManyToManyField(to='OoB.Tag')),
            ],
        ),
    ]
